-- Montreal Housing Intelligence -- analytical layer
-- GENERATED by scripts/generate_erd.py. Do not edit by hand:
-- re-run the script instead, or the diagram stops matching the database.
--
-- Columns and types come from information_schema on the live database.
-- Primary keys are the columns dbt declares both unique and not_null.
-- tested_*  : asserted by a dbt relationships test on every build.
-- derived_* : real edge, asserted one table upstream, and Power BI needs it.
--
-- dim_geography.geometry is PostGIS geometry(MultiPolygon, 4326),
-- rendered as TEXT because drawDB does not parse PostGIS types.

CREATE TABLE dim_date (
    date_key           DATE NOT NULL,
    calendar_year      INTEGER NOT NULL,
    quarter_start_date DATE NOT NULL,
    quarter_label      TEXT NOT NULL,
    PRIMARY KEY (date_key)
);

CREATE TABLE dim_geography (
    geography_key        TEXT NOT NULL,
    geography_type       TEXT NOT NULL,
    name                 TEXT NOT NULL,
    parent_geography_key TEXT,
    PRIMARY KEY (geography_key)
);

CREATE TABLE dim_property_type (
    property_type_code TEXT NOT NULL,
    sort_order         INTEGER NOT NULL,
    source_label_fr    TEXT NOT NULL,
    PRIMARY KEY (property_type_code),
    UNIQUE (source_label_fr),
    UNIQUE (sort_order)
);

CREATE TABLE dim_household_profile (
    household_profile_code TEXT NOT NULL,
    household_size_label   TEXT NOT NULL,
    household_type_label   TEXT NOT NULL,
    PRIMARY KEY (household_profile_code),
    UNIQUE (household_size_label),
    UNIQUE (household_type_label)
);

CREATE TABLE bridge_apciq_sector_geography (
    apciq_geography_key TEXT NOT NULL,
    admin_geography_key TEXT NOT NULL,
    coverage            TEXT NOT NULL
);

CREATE TABLE bridge_census_tract_apciq_sector (
    census_tract_geography_key TEXT NOT NULL,
    ct_uid                     TEXT NOT NULL,
    apciq_geography_key        TEXT NOT NULL,
    apciq_sector_number        INTEGER NOT NULL,
    population_weight          NUMERIC NOT NULL,
    weight_basis               TEXT NOT NULL,
    assignment_method          TEXT NOT NULL,
    tract_is_shared            BOOLEAN NOT NULL,
    includes_corrected_point   BOOLEAN NOT NULL,
    is_drawn_in_this_sector    BOOLEAN NOT NULL
);

CREATE TABLE fact_market (
    market_key                    TEXT NOT NULL,
    quarter_start_date            DATE NOT NULL,
    geography_key                 TEXT NOT NULL,
    property_type_code            TEXT NOT NULL,
    is_island_aggregate           BOOLEAN NOT NULL,
    sales_value_status            TEXT NOT NULL,
    active_listings_value_status  TEXT NOT NULL,
    median_price_value_status     TEXT NOT NULL,
    average_price_value_status    TEXT NOT NULL,
    days_on_market_value_status   TEXT NOT NULL,
    sales_corroboration           TEXT NOT NULL,
    active_listings_corroboration TEXT NOT NULL,
    source_page                   INTEGER NOT NULL,
    PRIMARY KEY (market_key)
);

CREATE TABLE fact_market_trailing_12m (
    trailing_key                  TEXT NOT NULL,
    period_start_date             DATE NOT NULL,
    period_end_date               DATE NOT NULL,
    geography_key                 TEXT NOT NULL,
    property_type_code            TEXT NOT NULL,
    is_island_aggregate           BOOLEAN NOT NULL,
    sales_value_status            TEXT NOT NULL,
    active_listings_value_status  TEXT NOT NULL,
    median_price_value_status     TEXT NOT NULL,
    average_price_value_status    TEXT NOT NULL,
    days_on_market_value_status   TEXT NOT NULL,
    sales_corroboration           TEXT NOT NULL,
    active_listings_corroboration TEXT NOT NULL,
    PRIMARY KEY (trailing_key)
);

CREATE TABLE fact_mortgage_scenario (
    mortgage_scenario_key   TEXT NOT NULL,
    contract_rate_percent   NUMERIC NOT NULL,
    posted_rate_percent     NUMERIC NOT NULL,
    rate_basis              TEXT NOT NULL,
    qualifying_rate_percent NUMERIC NOT NULL,
    income_required_basis   TEXT NOT NULL,
    insurance_status        TEXT NOT NULL,
    PRIMARY KEY (mortgage_scenario_key)
);

CREATE TABLE fact_affordability (
    affordability_key          TEXT NOT NULL,
    census_tract_geography_key TEXT NOT NULL,
    ct_uid                     TEXT NOT NULL,
    property_type_code         TEXT NOT NULL,
    household_profile_code     TEXT NOT NULL,
    assignment_method          TEXT NOT NULL,
    price_basis                TEXT NOT NULL,
    income_year                INTEGER NOT NULL,
    PRIMARY KEY (affordability_key)
);

CREATE TABLE dim_interest_rate_series (
    series_id        TEXT NOT NULL,
    sort_order       INTEGER NOT NULL,
    series_label     TEXT NOT NULL,
    rate_kind        TEXT NOT NULL,
    frequency        TEXT NOT NULL,
    is_mortgage_rate BOOLEAN NOT NULL,
    PRIMARY KEY (series_id),
    UNIQUE (series_label),
    UNIQUE (sort_order)
);

CREATE TABLE fact_interest_rate (
    interest_rate_key TEXT NOT NULL,
    series_id         TEXT NOT NULL,
    observation_date  DATE NOT NULL,
    rate_percent      NUMERIC NOT NULL,
    PRIMARY KEY (interest_rate_key)
);

-- Referential integrity, recovered from the dbt relationships tests.

ALTER TABLE dim_geography ADD CONSTRAINT tested_geography_nests_in_its_parent FOREIGN KEY (parent_geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE bridge_apciq_sector_geography ADD CONSTRAINT tested_bridge_names_an_apciq_sector FOREIGN KEY (apciq_geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE bridge_apciq_sector_geography ADD CONSTRAINT tested_bridge_names_an_admin_entity FOREIGN KEY (admin_geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE bridge_census_tract_apciq_sector ADD CONSTRAINT tested_bridge_names_a_census_tract FOREIGN KEY (census_tract_geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE bridge_census_tract_apciq_sector ADD CONSTRAINT tested_tract_sits_in_an_apciq_sector FOREIGN KEY (apciq_geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE fact_market ADD CONSTRAINT tested_market_is_dated_by_quarter FOREIGN KEY (quarter_start_date) REFERENCES dim_date(date_key);
ALTER TABLE fact_market ADD CONSTRAINT tested_market_is_measured_in_a_sector FOREIGN KEY (geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE fact_market ADD CONSTRAINT tested_market_is_split_by_property_type FOREIGN KEY (property_type_code) REFERENCES dim_property_type(property_type_code);
ALTER TABLE fact_market_trailing_12m ADD CONSTRAINT tested_trailing_12m_ends_on_a_date FOREIGN KEY (period_end_date) REFERENCES dim_date(date_key);
ALTER TABLE fact_market_trailing_12m ADD CONSTRAINT tested_trailing_12m_is_measured_in_a_sector FOREIGN KEY (geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE fact_market_trailing_12m ADD CONSTRAINT tested_trailing_12m_is_split_by_property_type FOREIGN KEY (property_type_code) REFERENCES dim_property_type(property_type_code);
ALTER TABLE fact_mortgage_scenario ADD CONSTRAINT tested_one_scenario_per_market_row FOREIGN KEY (mortgage_scenario_key) REFERENCES fact_market(market_key);
ALTER TABLE fact_affordability ADD CONSTRAINT tested_affordability_is_split_by_property_type FOREIGN KEY (property_type_code) REFERENCES dim_property_type(property_type_code);
ALTER TABLE fact_affordability ADD CONSTRAINT tested_affordability_is_split_by_household FOREIGN KEY (household_profile_code) REFERENCES dim_household_profile(household_profile_code);
ALTER TABLE fact_affordability ADD CONSTRAINT tested_affordability_is_measured_in_a_tract FOREIGN KEY (census_tract_geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE fact_interest_rate ADD CONSTRAINT tested_fact_interest_rate__series_id FOREIGN KEY (series_id) REFERENCES dim_interest_rate_series(series_id);
ALTER TABLE fact_interest_rate ADD CONSTRAINT tested_fact_interest_rate__observation_date FOREIGN KEY (observation_date) REFERENCES dim_date(date_key);
