-- Montreal Housing Intelligence -- analytical layer
-- GENERATED by scripts/generate_erd.py. Do not edit by hand:
-- re-run the script instead, or the diagram stops matching the database.
--
-- Columns and types come from information_schema on the live database.
-- Primary keys are the columns dbt declares both unique and not_null.
-- tested_*  : asserted by a dbt relationships test on every build.
-- derived_* : real edge, asserted one table upstream, and Power BI needs it.
--
-- dim_geography.geometry is PostGIS geometry(MultiPolygon, 4326),
-- rendered as TEXT because drawDB does not parse PostGIS types.

CREATE TABLE dim_date (
    date_key           DATE NOT NULL,
    calendar_year      INTEGER NOT NULL,
    calendar_quarter   INTEGER,
    calendar_month     INTEGER,
    day_of_month       INTEGER,
    quarter_start_date DATE NOT NULL,
    quarter_end_date   DATE,
    quarter_label      TEXT NOT NULL,
    month_start_date   DATE,
    month_end_date     DATE,
    iso_day_of_week    INTEGER,
    is_weekend         BOOLEAN,
    is_quarter_end     BOOLEAN,
    PRIMARY KEY (date_key)
);

CREATE TABLE dim_geography (
    geography_key        TEXT NOT NULL,
    geography_type       TEXT NOT NULL,
    geography_code       TEXT,
    name                 TEXT NOT NULL,
    parent_geography_key TEXT,
    geometry             TEXT,
    area_km2             NUMERIC,
    area_basis           TEXT,
    PRIMARY KEY (geography_key)
);

CREATE TABLE dim_property_type (
    property_type_code TEXT NOT NULL,
    sort_order         INTEGER NOT NULL,
    name_en            TEXT,
    source_label_fr    TEXT NOT NULL,
    PRIMARY KEY (property_type_code),
    UNIQUE (source_label_fr),
    UNIQUE (sort_order)
);

CREATE TABLE dim_household_profile (
    household_profile_code TEXT NOT NULL,
    sort_order             INTEGER,
    name_en                TEXT,
    household_size_label   TEXT NOT NULL,
    household_type_label   TEXT NOT NULL,
    PRIMARY KEY (household_profile_code),
    UNIQUE (household_size_label),
    UNIQUE (household_type_label)
);

CREATE TABLE bridge_apciq_sector_geography (
    apciq_geography_key    TEXT NOT NULL,
    apciq_sector_number    INTEGER,
    apciq_sector_name      TEXT,
    admin_geography_key    TEXT NOT NULL,
    codemamh               TEXT,
    admin_name             TEXT,
    admin_geography_type   TEXT,
    coverage               TEXT NOT NULL,
    component_label_source TEXT
);

CREATE TABLE bridge_census_tract_apciq_sector (
    census_tract_geography_key TEXT NOT NULL,
    ct_uid                     TEXT NOT NULL,
    apciq_geography_key        TEXT NOT NULL,
    apciq_sector_number        INTEGER NOT NULL,
    population_weight          NUMERIC NOT NULL,
    weight_basis               TEXT NOT NULL,
    population_in_sector       NUMERIC,
    tract_population           NUMERIC,
    dissemination_area_count   BIGINT,
    assignment_method          TEXT NOT NULL,
    neighbourhood_names        TEXT,
    tract_is_shared            BOOLEAN NOT NULL,
    sectors_touched            BIGINT,
    includes_corrected_point   BOOLEAN NOT NULL
);

CREATE TABLE fact_market (
    market_key                     TEXT NOT NULL,
    quarter_start_date             DATE NOT NULL,
    quarter_end_date               DATE,
    edition_year                   INTEGER,
    edition_quarter                INTEGER,
    edition_label                  TEXT,
    geography_key                  TEXT NOT NULL,
    area_code                      TEXT,
    property_type_code             TEXT NOT NULL,
    is_island_aggregate            BOOLEAN NOT NULL,
    sales_count                    BIGINT,
    active_listings                BIGINT,
    median_price                   BIGINT,
    average_price                  BIGINT,
    days_on_market                 BIGINT,
    sales_count_change_pct_yoy     INTEGER,
    active_listings_change_pct_yoy INTEGER,
    median_price_change_pct_yoy    INTEGER,
    average_price_change_pct_yoy   INTEGER,
    days_on_market_change_pct_yoy  INTEGER,
    sales_value_status             TEXT NOT NULL,
    active_listings_value_status   TEXT NOT NULL,
    median_price_value_status      TEXT NOT NULL,
    average_price_value_status     TEXT NOT NULL,
    days_on_market_value_status    TEXT NOT NULL,
    sales_corroboration            TEXT NOT NULL,
    active_listings_corroboration  TEXT NOT NULL,
    source_pdf                     TEXT,
    source_page                    INTEGER NOT NULL,
    first_seen_at                  TIMESTAMP,
    updated_at                     TIMESTAMP,
    PRIMARY KEY (market_key)
);

CREATE TABLE fact_market_trailing_12m (
    trailing_key                   TEXT NOT NULL,
    period_start_date              DATE NOT NULL,
    period_end_date                DATE NOT NULL,
    edition_year                   INTEGER,
    edition_quarter                INTEGER,
    edition_label                  TEXT,
    edition_quarter_start_date     DATE,
    geography_key                  TEXT NOT NULL,
    area_code                      TEXT,
    property_type_code             TEXT NOT NULL,
    is_island_aggregate            BOOLEAN NOT NULL,
    sales_count                    BIGINT,
    active_listings                BIGINT,
    median_price                   BIGINT,
    average_price                  BIGINT,
    days_on_market                 BIGINT,
    sales_count_change_pct_yoy     INTEGER,
    active_listings_change_pct_yoy INTEGER,
    median_price_change_pct_yoy    INTEGER,
    average_price_change_pct_yoy   INTEGER,
    days_on_market_change_pct_yoy  INTEGER,
    sales_value_status             TEXT NOT NULL,
    active_listings_value_status   TEXT NOT NULL,
    median_price_value_status      TEXT NOT NULL,
    average_price_value_status     TEXT NOT NULL,
    days_on_market_value_status    TEXT NOT NULL,
    sales_corroboration            TEXT NOT NULL,
    active_listings_corroboration  TEXT NOT NULL,
    source_pdf                     TEXT,
    source_page                    INTEGER,
    first_seen_at                  TIMESTAMP,
    updated_at                     TIMESTAMP,
    PRIMARY KEY (trailing_key)
);

CREATE TABLE fact_mortgage_scenario (
    mortgage_scenario_key             TEXT NOT NULL,
    quarter_start_date                DATE,
    quarter_end_date                  DATE,
    edition_year                      INTEGER,
    edition_quarter                   INTEGER,
    edition_label                     TEXT,
    geography_key                     TEXT,
    area_code                         TEXT,
    property_type_code                TEXT,
    is_island_aggregate               BOOLEAN,
    median_price                      BIGINT,
    median_price_value_status         TEXT,
    contract_rate_percent             NUMERIC NOT NULL,
    contract_rate_observation_count   BIGINT,
    posted_rate_percent               NUMERIC NOT NULL,
    posted_rate_observation_count     BIGINT,
    posted_minus_contract_rate_points NUMERIC,
    rate_basis                        TEXT NOT NULL,
    down_payment_scenario             TEXT,
    amortization_years                NUMERIC,
    qualifying_rate_percent           NUMERIC NOT NULL,
    minimum_down_payment              NUMERIC,
    loan_to_value                     NUMERIC,
    insurance_premium_rate            NUMERIC,
    insurance_premium                 NUMERIC,
    loan_amount                       NUMERIC,
    monthly_payment_contract_rate     NUMERIC,
    monthly_payment_qualifying_rate   NUMERIC,
    income_required_lower_bound       NUMERIC,
    income_required_basis             TEXT NOT NULL,
    insurance_status                  TEXT NOT NULL,
    PRIMARY KEY (mortgage_scenario_key)
);

CREATE TABLE fact_affordability (
    affordability_key               TEXT NOT NULL,
    quarter_start_date              DATE,
    quarter_end_date                DATE,
    edition_year                    INTEGER,
    edition_quarter                 INTEGER,
    edition_label                   TEXT,
    census_tract_geography_key      TEXT NOT NULL,
    ct_uid                          TEXT NOT NULL,
    property_type_code              TEXT NOT NULL,
    household_profile_code          TEXT NOT NULL,
    household_profile_sort_order    INTEGER,
    apciq_geography_key             TEXT,
    apciq_sector_number             INTEGER,
    area_code                       TEXT,
    assignment_method               TEXT NOT NULL,
    neighbourhood_names             TEXT,
    tract_is_shared                 BOOLEAN,
    population_weight               NUMERIC,
    weight_basis                    TEXT,
    tract_population                NUMERIC,
    median_price                    BIGINT,
    median_price_value_status       TEXT,
    price_basis                     TEXT NOT NULL,
    household_income                NUMERIC,
    household_income_status         TEXT,
    household_count                 INTEGER,
    household_count_status          TEXT,
    income_year                     INTEGER NOT NULL,
    price_year_minus_income_year    INTEGER,
    contract_rate_percent           NUMERIC,
    qualifying_rate_percent         NUMERIC,
    amortization_years              NUMERIC,
    monthly_payment_qualifying_rate NUMERIC,
    income_required_lower_bound     NUMERIC,
    income_required_basis           TEXT,
    insurance_status                TEXT,
    price_to_income_ratio           NUMERIC,
    income_shortfall                NUMERIC,
    meets_income_requirement        BOOLEAN,
    PRIMARY KEY (affordability_key)
);

CREATE TABLE apciq_known_publisher_defect (
    edition_year    INTEGER,
    edition_quarter INTEGER,
    control_code    TEXT,
    metric_code     TEXT,
    verified_on     DATE,
    finding         TEXT
);

CREATE TABLE apciq_sector_composition (
    apciq_sector_number    INTEGER,
    apciq_sector_name      TEXT,
    component_label_source TEXT,
    codemamh               TEXT,
    coverage               TEXT
);

CREATE TABLE apciq_sector_neighbourhood (
    source_dataset            TEXT,
    neighbourhood_code        TEXT,
    neighbourhood_name_source TEXT,
    borough_codemamh          TEXT,
    apciq_sector_number       INTEGER
);

CREATE TABLE mortgage_down_payment_bracket (
    rule_id           TEXT,
    price_from_cad    NUMERIC,
    price_to_cad      NUMERIC,
    tranche_from_cad  NUMERIC,
    tranche_to_cad    NUMERIC,
    down_payment_rate NUMERIC,
    source_url        TEXT,
    retrieved_on      DATE,
    published_wording TEXT
);

CREATE TABLE mortgage_insurance_premium_band (
    amortization_years INTEGER,
    ltv_from           NUMERIC,
    ltv_to             NUMERIC,
    down_payment_kind  TEXT,
    premium_rate       NUMERIC,
    value_basis        TEXT,
    source_url         TEXT,
    retrieved_on       DATE
);

CREATE TABLE mortgage_underwriting_parameter (
    parameter_name    TEXT,
    parameter_value   NUMERIC,
    unit              TEXT,
    applies_to        TEXT,
    value_basis       TEXT,
    source_url        TEXT,
    retrieved_on      DATE,
    published_wording TEXT
);

CREATE TABLE statcan_misplaced_representative_point (
    da_uid                      TEXT,
    ct_uid                      TEXT,
    point_falls_in_codemamh     TEXT,
    tract_mostly_in_codemamh    TEXT,
    tract_share_of_majority_pct NUMERIC,
    da_land_area_km2            NUMERIC,
    room_in_assignment_km2      NUMERIC,
    size_ratio                  NUMERIC,
    population_2021             INTEGER,
    resolution                  TEXT,
    verified_on                 DATE,
    finding                     TEXT
);

-- Referential integrity, recovered from the dbt relationships tests.

ALTER TABLE dim_geography ADD CONSTRAINT tested_geography_nests_in_its_parent FOREIGN KEY (parent_geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE bridge_apciq_sector_geography ADD CONSTRAINT tested_bridge_names_an_apciq_sector FOREIGN KEY (apciq_geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE bridge_apciq_sector_geography ADD CONSTRAINT tested_bridge_names_an_admin_entity FOREIGN KEY (admin_geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE bridge_census_tract_apciq_sector ADD CONSTRAINT tested_bridge_names_a_census_tract FOREIGN KEY (census_tract_geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE bridge_census_tract_apciq_sector ADD CONSTRAINT tested_tract_sits_in_an_apciq_sector FOREIGN KEY (apciq_geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE fact_market ADD CONSTRAINT tested_market_is_dated_by_quarter FOREIGN KEY (quarter_start_date) REFERENCES dim_date(date_key);
ALTER TABLE fact_market ADD CONSTRAINT tested_market_is_measured_in_a_sector FOREIGN KEY (geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE fact_market ADD CONSTRAINT tested_market_is_split_by_property_type FOREIGN KEY (property_type_code) REFERENCES dim_property_type(property_type_code);
ALTER TABLE fact_market_trailing_12m ADD CONSTRAINT tested_trailing_12m_ends_on_a_date FOREIGN KEY (period_end_date) REFERENCES dim_date(date_key);
ALTER TABLE fact_market_trailing_12m ADD CONSTRAINT tested_trailing_12m_is_measured_in_a_sector FOREIGN KEY (geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE fact_market_trailing_12m ADD CONSTRAINT tested_trailing_12m_is_split_by_property_type FOREIGN KEY (property_type_code) REFERENCES dim_property_type(property_type_code);
ALTER TABLE fact_mortgage_scenario ADD CONSTRAINT tested_one_scenario_per_market_row FOREIGN KEY (mortgage_scenario_key) REFERENCES fact_market(market_key);
ALTER TABLE fact_affordability ADD CONSTRAINT tested_affordability_is_split_by_property_type FOREIGN KEY (property_type_code) REFERENCES dim_property_type(property_type_code);
ALTER TABLE fact_affordability ADD CONSTRAINT tested_affordability_is_split_by_household FOREIGN KEY (household_profile_code) REFERENCES dim_household_profile(household_profile_code);
ALTER TABLE fact_affordability ADD CONSTRAINT tested_affordability_is_measured_in_a_tract FOREIGN KEY (census_tract_geography_key) REFERENCES dim_geography(geography_key);

-- Star-schema edges Power BI needs, asserted one table upstream.

ALTER TABLE fact_mortgage_scenario ADD CONSTRAINT derived_scenario_is_dated_by_quarter FOREIGN KEY (quarter_start_date) REFERENCES dim_date(date_key);
ALTER TABLE fact_mortgage_scenario ADD CONSTRAINT derived_scenario_is_measured_in_a_sector FOREIGN KEY (geography_key) REFERENCES dim_geography(geography_key);
ALTER TABLE fact_mortgage_scenario ADD CONSTRAINT derived_scenario_is_split_by_property_type FOREIGN KEY (property_type_code) REFERENCES dim_property_type(property_type_code);
ALTER TABLE fact_affordability ADD CONSTRAINT derived_affordability_is_dated_by_quarter FOREIGN KEY (quarter_start_date) REFERENCES dim_date(date_key);
ALTER TABLE fact_affordability ADD CONSTRAINT derived_affordability_borrows_a_sector_price FOREIGN KEY (apciq_geography_key) REFERENCES dim_geography(geography_key);
