"""Generate the dbt DAG of this project as a mermaid diagram.

WHY THIS SCRIPT EXISTS
----------------------
`docs/architecture.md` described the transformation layer as "staging 9 views
-> intermediate 2 views -> marts 14 tables" without naming a single model. A
reader could not tell where `fact_affordability` comes from without opening the
SQL, and the ERD does not answer it either: the ERD shows which tables share a
key, not which model builds which.

Drawing that graph by hand would produce a picture that is true the day it is
drawn and quietly false after the next model is added. So this script reads it
from the only source of truth there is:

    dbt/target/manifest.json    written by `dbt parse`, `dbt ls`, `dbt build`

Nothing is drawn from memory. Re-running the script after adding a model is
what stops the diagram from becoming a lie -- the same argument that justifies
`scripts/generate_erd.py`, and the same failure mode it avoids.

WHAT THE DIAGRAM IS ALLOWED TO CLAIM
------------------------------------
Every arrow is a real dependency recorded in the manifest. There are two
deliberate foldings, and neither one makes an arrow less exact:

  * The 10 `raw` tables are not drawn. Section 1 of architecture.md already
    shows them, and a staging model is 1:1 with its raw table.
  * The seeds are folded into ONE box, labelled with how many of them the
    drawn models actually read. Every arrow leaving it is a real
    dependency of the model it points at. The box is a bag of published
    parameter tables, not a layer.

What is NEVER done here: folding several staging models of one publisher into
a single box. It would cut the picture almost in half, and it would assert
that `fact_affordability` depends on every Statistics Canada model when it
depends on two of four. A diagram in this repository only claims what is true.

Model names drop the prefix their subgraph already carries, so
`stg_statcan__census_tracts` inside "Statistics Canada" reads `census_tracts`.
Measured on this project: that single change is what takes the picture from
unreadable to readable -- the full names run to 48 characters, and the layout
engine spends the width on them instead of on the edges.

The dimensions no dbt model reads -- today `dim_date`, `dim_property_type` and
`dim_interest_rate_series` -- are listed in one annotated box instead of being
drawn as orphan rectangles. They are declared tables that only Power BI reads;
a floating box with no arrow reads as a mistake rather than as a fact.

Usage (Git Bash or PowerShell, from the repo root). The script itself never
touches the database -- it only reads the manifest on disk:

    .venv/Scripts/python.exe scripts/generate_dbt_dag.py --inject docs/architecture.md
    .venv/Scripts/python.exe scripts/generate_dbt_dag.py --check docs/architecture.md
    .venv/Scripts/python.exe scripts/generate_dbt_dag.py --out docs/erd/mhi-dbt-dag.mmd
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = REPO_ROOT / "dbt" / "target" / "manifest.json"

# The publishers, in the order they should appear top to bottom. Each one is a
# subgraph title; the staging models inside it are read from the manifest, so
# adding a model to a publisher needs no change here.
PUBLISHERS = [
    ("apciq", "APCIQ"),
    ("bank_of_canada", "Bank of Canada"),
    ("statcan", "Statistics Canada"),
    ("montreal_open_data", "Donnees Montreal"),
]

BEGIN = "<!-- dbt-dag:begin -- generated by scripts/generate_dbt_dag.py, do not edit by hand -->"
END = "<!-- dbt-dag:end -->"


def load_manifest() -> tuple[dict, dict]:
    if not MANIFEST.exists():
        raise SystemExit(
            f"No manifest at {MANIFEST.relative_to(REPO_ROOT)}.\n"
            "Run `bash scripts/dbt.sh parse` first. The wrapper wants the tunnel "
            "open, like every dbt command here; any `dbt build` rewrites it too."
        )
    doc = json.loads(MANIFEST.read_text(encoding="utf-8"))
    nodes = doc["nodes"]
    models = {k: n for k, n in nodes.items() if n["resource_type"] == "model"}
    seeds = {k: n for k, n in nodes.items() if n["resource_type"] == "seed"}
    return models, seeds


def build(models: dict, seeds: dict, keep: set | None = None) -> tuple[str, dict]:
    name = lambda k: models[k]["name"] if k in models else seeds[k]["name"]
    layer = lambda k: models[k]["path"].replace("\\", "/").split("/")[0]
    parents = {k: models[k]["depends_on"]["nodes"] for k in models}
    children = {k: [c for c in models if k in parents[c]] for k in models}

    def publisher_of(k: str) -> str | None:
        n = name(k)
        for key, _ in PUBLISHERS:
            if f"_{key}__" in n or n.startswith(f"stg_{key}"):
                return key
        return None

    def short(k: str) -> str:
        """Drop the prefix the enclosing subgraph already states."""
        n = name(k)
        return n.split("__", 1)[1] if "__" in n else n

    # A model no other model reads AND that reads nothing is declared, not
    # derived: dbt builds it from a VALUES list and only Power BI consumes it.
    declared = sorted(
        (k for k in models if layer(k) == "marts" and not parents[k] and not children[k]),
        key=name,
    )
    drawn = [k for k in models if k not in declared]
    if keep is not None:
        # --select: the neighbourhood asked for, declared dimensions dropped
        # unless they are in it.
        drawn = [k for k in drawn if k in keep]
        declared = [k for k in declared if k in keep]

    lines = ["flowchart LR"]
    for key, label in PUBLISHERS:
        members = sorted((k for k in drawn if layer(k) == "staging" and publisher_of(k) == key), key=name)
        if not members:
            continue
        lines.append(f'  subgraph STG_{key}["{label}"]')
        lines += [f'    {name(k)}["{short(k)}"]' for k in members]
        lines.append("  end")

    intermediate = sorted((k for k in drawn if layer(k) == "intermediate"), key=name)
    if intermediate:
        lines.append('  subgraph INT["intermediate"]')
        lines += [f'    {name(k)}["{short(k)}"]' for k in intermediate]
        lines.append("  end")

    # Count the seeds THESE models actually read. On the full graph that is all
    # of them; on a --select excerpt, saying "7 seeds" would claim more than the
    # picture shows.
    used_seeds = {p for k in drawn for p in parents[k] if p in seeds}
    if used_seeds:
        plural = "seeds" if len(used_seeds) > 1 else "seed"
        lines.append(f'  SEEDS[/"{len(used_seeds)} {plural}<br/>published parameters"/]')

    marts = sorted((k for k in drawn if layer(k) == "marts"), key=name)
    lines.append('  subgraph MARTS["marts"]')
    lines += [f'    {name(k)}["{short(k)}"]' for k in marts]
    lines.append("  end")

    if declared:
        listed = "<br/>".join(short(k) for k in declared)
        lines.append(
            f'  DECLARED["{len(declared)} declared dimensions<br/>{listed}<br/>'
            'no dbt parent, read by Power BI"]'
        )

    # Edges last, de-duplicated among themselves only -- the structural lines
    # above repeat (every subgraph ends with the same `end`) and must not be.
    edges: list[str] = []
    for k in drawn:
        for p in parents[k]:
            if p in models and p in drawn:
                edges.append(f"  {name(p)} --> {name(k)}")
            elif p in seeds:
                edges.append(f"  SEEDS --> {name(k)}")
    lines += list(dict.fromkeys(edges))

    counts = {
        "models": len(models),
        "drawn": len(drawn),
        "declared": len(declared),
        "seeds": len(used_seeds),
        "edges": len(set(edges)),
    }
    return "\n".join(lines), counts


def neighbourhood(models: dict, target_name: str, depth: int) -> set:
    """The model, its ancestors and its descendants, up to `depth` hops.

    Depth 1 is what a lineage panel shows by default: the model and what it
    directly touches. It is also what makes a picture readable -- measured on
    this project, the full ancestry of `fact_affordability` is 32 nodes out of
    42, which is not an excerpt at all.
    """
    matches = [k for k, n in models.items() if n["name"] == target_name]
    if not matches:
        raise SystemExit(
            f"No model named {target_name!r}. Known models:\n  "
            + "\n  ".join(sorted(n["name"] for n in models.values()))
        )
    target = matches[0]
    parents = {k: models[k]["depends_on"]["nodes"] for k in models}
    keep = {target}
    frontier_up = frontier_down = {target}
    for _ in range(depth):
        up = {p for k in frontier_up for p in parents[k] if p in models} - keep
        down = {c for c in models if any(k in parents[c] for k in frontier_down)} - keep
        keep |= up | down
        frontier_up, frontier_down = up, down
    return keep


def rel(path: Path) -> str:
    """Path as the reader typed it, never raising.

    `Path("docs/x.md").relative_to(REPO_ROOT)` raises, because a relative path
    is not "under" an absolute one as far as pathlib is concerned. The same
    mistake in scripts/generate_erd.py crashed AFTER the file had been written
    -- a failure that looks like one and is not.
    """
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def fenced(diagram: str) -> str:
    return f"{BEGIN}\n\n```mermaid\n{diagram}\n```\n\n{END}"


def inject(target: Path, diagram: str, check_only: bool) -> int:
    text = target.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SystemExit(
            f"{rel(target)} carries no dbt-dag markers.\n"
            f"Add these two lines where the diagram belongs:\n  {BEGIN}\n  {END}"
        )
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = head + fenced(diagram) + tail
    if updated == text:
        print(f"{rel(target)} is up to date.")
        return 0
    if check_only:
        print(
            f"STALE: {rel(target)} does not match the manifest.\n"
            "Run: .venv/Scripts/python.exe scripts/generate_dbt_dag.py --inject "
            f"{rel(target)}"
        )
        return 1
    target.write_text(updated, encoding="utf-8")
    print(f"Updated {rel(target)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the dbt DAG of this project as a mermaid diagram."
    )
    parser.add_argument("--inject", type=Path, metavar="MARKDOWN",
                        help="Replace the diagram between the markers in this file.")
    parser.add_argument("--check", type=Path, metavar="MARKDOWN",
                        help="Exit 1 if that file's diagram no longer matches the manifest.")
    parser.add_argument("--out", type=Path, help="Write the bare mermaid source to this file.")
    parser.add_argument("--select", metavar="MODEL",
                        help="Draw only this model and its neighbours, like a lineage panel.")
    parser.add_argument("--depth", type=int, default=1,
                        help="How many hops --select reaches, upstream and downstream (default 1).")
    args = parser.parse_args()

    models, seeds = load_manifest()
    keep = neighbourhood(models, args.select, args.depth) if args.select else None
    diagram, counts = build(models, seeds, keep)

    print(
        f"{counts['models']} models: {counts['drawn']} drawn, "
        f"{counts['declared']} listed as declared | {counts['seeds']} seeds folded into one box | "
        f"{counts['edges']} edges"
    )

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(diagram + "\n", encoding="utf-8")
        print(f"Wrote {rel(args.out)}")
    if args.check:
        return inject(args.check, diagram, check_only=True)
    if args.inject:
        return inject(args.inject, diagram, check_only=False)
    if not args.out:
        print()
        print(fenced(diagram))
    return 0


if __name__ == "__main__":
    sys.exit(main())
